version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "consumerg"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-aw3uffykoyja"
s3_prefix = "consumerg"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
